apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate 
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
        env: prod
    spec:
      containers:
      - name: nodeserver
        image: aymenchab/apptest:1.0

