apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: NodePort
  selector:
    app: nodeapp 
    env: prod
  ports:
  - name: test2
    protocol: TCP
    port: 3500
    targetPort: 3500
    nodePort: 30001
